### ISSUE TITLE
issues installing ZooSVD

### ISSUE THREAD

**Issue by iancharest** [MoiseRousseau/ZooSVD#1]
```bash
cmake .. DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=1
```
should read:

```bash
cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=1
```

In addition, despite having the latest lapack packages installed on my ubuntu 22.04 machine, I get this error with cmake:

```bash
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LAPACKE (missing: LAPACKE_LIBRARIES LAPACKE_WORKS)
  ```

**Comment by MoiseRousseau** [comment]
Hi Ian,

Thanks for reporting this. I made a mistake in the installation instruction for -DCMAKE_BUILD_TYPE=Release and I forgot to add dependencies for LAPACKE package. To install it on Ubuntu:
```
apt install liblapacke-dev
```

Edit: Installation instructions were just updated, see https://github.com/MoiseRousseau/ZooSVD/commit/bd77c32f6c903cd72c0e680696b00c68d6a88080 

Let me know if you are able to install it now,
Moise

**Comment by iancharest** [comment]
Hi Moise,

thanks for updating this.

I can now close this issue as everything is working.

ian
